spring:
  profiles:
    active: local

management:
  security:
    enabled: false
---
spring:
  profiles: dev
  data:
    mongodb:
      host: mongodb.testando.kinghost.com.br
      username: testando01
      password: testando01
      database: testando01	 
      port: 27017	  
      repositories:
        enabled: true

server:
  port: 1000
  
---
spring:
  profiles: local
  data:
    mongodb:
      host: mongodb.testando.kinghost.com.br
      username: testando01
      password: testando01
      database: testando01	 
      port: 27017	  
      repositories:
        enabled: true

server:
  port: 2000