spring:
  profiles:
    active: local

server:
  port: 1028

management:
  security:
    enabled: false
---
spring:
  profiles: dev
  data:
    mongodb:
      host: mongodb://mongo.server:27017/catalogo
      username: testando01
      password: testando01
      database: testando01	 
      port: 27017	  
      repositories:
        enabled: true
